name: Datapack error check on PR

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Installing additional packages
        run: sudo apt-get install -y python3-pip && sudo pip install hjson

      - name: Checking for errors
        run: scripts/lint.sh
